services:
  - type: web
    name: td-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install 'uvicorn[standard]'
    startCommand: "python -m uvicorn api.main:app --host 0.0.0.0 --port $PORT --reload"
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: .

  - type: web
    name: td-dashboard
    env: python
    buildCommand: |
      pip install -r requirements.txt
      pip install streamlit --upgrade
    startCommand: "python -m streamlit run frontend/dashboard.py --server.port=$PORT --server.address=0.0.0.0 --server.enableXsrfProtection=false"
    envVars:
      - key: PORT
        value: 8501
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: . 